#!/usr/bin/env python3
"""Reliable host-side bridge from MCP/CLI to Rhino 8's rhinocode CLI.

IMPORTANT: subprocess is used here in the external MCP process, never inside Rhino.
"""
from __future__ import annotations

import json
import os
import subprocess
import tempfile
import time
import uuid
from pathlib import Path
from typing import Any

RHINOCODE = Path(os.environ.get(
    "RHINOCODE_PATH",
    "/Applications/Rhino 8.app/Contents/Resources/bin/rhinocode",
))
DEFAULT_TIMEOUT = float(os.environ.get("RHINO_MCP_TIMEOUT", "30"))


class RhinoBridgeError(RuntimeError):
    pass


def _run_cli(*args: str, timeout: float = 10.0) -> subprocess.CompletedProcess[str]:
    if not RHINOCODE.exists():
        raise RhinoBridgeError(f"rhinocode not found: {RHINOCODE}")
    return subprocess.run(
        [str(RHINOCODE), *args],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def status() -> dict[str, Any]:
    """Return rhinocode/Rhino availability. Never relies on script exit codes."""
    try:
        cp = _run_cli("list")
    except Exception as exc:
        return {"ok": False, "error": str(exc), "rhinocode": str(RHINOCODE)}
    text = (cp.stdout or "").strip()
    return {
        "ok": bool(text),
        "rhinocode": str(RHINOCODE),
        "instances_raw": text,
        "stderr": (cp.stderr or "").strip(),
    }


def execute(code: str, timeout: float | None = None, operation: str = "mcp",
            undoable: bool = True) -> dict[str, Any]:
    """Execute Python inside active Rhino and synchronously return structured JSON.

    rhinocode itself is async/fire-and-forget, so this creates a unique script/result
    pair and polls the result file until Rhino signals completion.
    The executed code may assign a JSON-serializable value to ``result``.

    Rhino automatically wraps each rhinocode script execution in its own undo record,
    so each call is already undoable as a single Cmd+Z step. The *undoable* parameter
    is accepted for API compatibility but has no effect (BeginUndoRecord returns 0
    inside rhinocode's execution context).
    """
    timeout = DEFAULT_TIMEOUT if timeout is None else float(timeout)
    st = status()
    if not st.get("ok"):
        return {"ok": False, "kind": "rhino_unavailable", "status": st}

    op_id = uuid.uuid4().hex
    base = Path(tempfile.gettempdir()) / "rhino-cad-mcp"
    base.mkdir(parents=True, exist_ok=True)
    script_path = base / f"{op_id}.py"
    result_path = base / f"{op_id}.json"

    payload = _make_harness(code, result_path, op_id, operation)
    script_path.write_text(payload, encoding="utf-8")
    started = time.monotonic()
    try:
        # This process only submits the job; completion is detected by the result file.
        cp = _run_cli("script", str(script_path), timeout=max(10.0, timeout))
        deadline = started + timeout
        while time.monotonic() < deadline:
            if result_path.exists():
                try:
                    data = json.loads(result_path.read_text(encoding="utf-8"))
                except Exception as exc:
                    return {"ok": False, "kind": "malformed_result", "error": str(exc), "operation_id": op_id}
                data["bridge_elapsed_ms"] = round((time.monotonic() - started) * 1000, 1)
                data["rhinocode_submit_stdout"] = (cp.stdout or "").strip()
                data["rhinocode_submit_stderr"] = (cp.stderr or "").strip()
                return data
            time.sleep(0.05)
        return {
            "ok": False,
            "kind": "timeout",
            "operation_id": op_id,
            "timeout_seconds": timeout,
            "note": "The Rhino script may still be queued/running; rhinocode is asynchronous.",
        }
    finally:
        # Result has been read into memory. Keep viewport images, remove transient IPC files.
        try:
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        try:
            result_path.unlink(missing_ok=True)
        except Exception:
            pass


def _make_harness(code: str, result_path: Path, op_id: str, operation: str) -> str:
    # Must remain Python 3.9-compatible because it runs inside Rhino.
    return f'''# Auto-generated by rhino-cad-mcp. Python 3.9 compatible.
import contextlib
import io
import json
import time
import traceback
from pathlib import Path

_RESULT_PATH = Path({str(result_path)!r})
_OPERATION_ID = {op_id!r}
_OPERATION = {operation!r}
_started = time.time()
_stdout = io.StringIO()
result = None

def _json_default(obj):
    try:
        return str(obj)
    except Exception:
        return "<unserializable>"

try:
    with contextlib.redirect_stdout(_stdout), contextlib.redirect_stderr(_stdout):
{_indent(code, 8)}
    _payload = {{
        "ok": True,
        "operation_id": _OPERATION_ID,
        "operation": _OPERATION,
        "result": result,
        "console": _stdout.getvalue(),
        "rhino_elapsed_ms": round((time.time() - _started) * 1000, 1),
    }}
except Exception as exc:
    _payload = {{
        "ok": False,
        "kind": "python_exception",
        "operation_id": _OPERATION_ID,
        "operation": _OPERATION,
        "error": str(exc),
        "traceback": traceback.format_exc(),
        "console": _stdout.getvalue(),
        "rhino_elapsed_ms": round((time.time() - _started) * 1000, 1),
    }}
finally:
    _tmp = Path(str(_RESULT_PATH) + ".tmp")
    _tmp.write_text(json.dumps(_payload, default=_json_default), encoding="utf-8")
    _tmp.replace(_RESULT_PATH)
'''


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    lines = text.splitlines() or ["pass"]
    return "\n".join(pad + line for line in lines)
